### PR TITLE
[DEV] Automatic event subscription for systems.

### PR DESCRIPTION
**Pull request by rcorre**
Add an AutoSubscribe parameter to SystemManager.register/unregister.
When yes (the default), automatically subscribe the newly registered
system to any event E for which it implements Receiver!E.
Similarly, this applies to unregister and unsubscribing from events.

This will not work if the argument passed is an ISystem -- it must be
the full type implementing the Receiver interfaces.

This avoids the finicky business of adding new event receivers and
forgetting to subscribe them to the events, as now it is implicit in
registering the system.

### CODE REVIEW

**Comment by rcorre** [comment]
This is just an idea -- not sure if its more complexity than necessary.
I just noticed it is easy to forget a call to `subscribe` when you implement a new `Receiver`, and so far 100% of the time I've wanted my `Receivers` to be subscribed.
Then again, maybe in a larger game you would want to subscribe selectively, so maybe `no` is a better default...

**Comment by claudemr** [comment]
Thanks, that's a nice addition!

Indeed, we can keep "yes" as a default.

For the alias of the flag, I came across a [discussion](http://forum.dlang.org/thread/n7rbm7$2s20$1@digitalmars.com?page=1) on D-idiom about them. A. Alexandrescu has a point. So, well, just for the sake of it...

I'll remove the exception throwing in event subscription. It breaks the current example code (event subscribed twice due to the automatic subscription), and they are not very useful there.

**Comment by rcorre** [comment]
Yeah, I saw that discussion, but I'm not quite sure how I feel about it. I initially agreed with the opinions Jack Stouffer and H. S. Teoh express later in the thread, but after reading again I'm coming around to Andrei's way of thinking.

And yes, I don't think throwing on re-subscription is necessary. It should probably be a silent no-op.

On February 25, 2016 9:34:06 AM EST, claudemr notifications@github.com wrote:

> Thanks, that's a nice addition!
> 
> Indeed, we can keep "yes" as a default.
> 
> For the alias of the flag, I came across a
> [discussion](http://forum.dlang.org/thread/n7rbm7$2s20$1@digitalmars.com?page=1)
> on D-idiom about them. A. Alexandrescu has a point. So, well, just for
> the sake of it...
> 
> I'll remove the exception throwing in event subscription. It breaks the
> current example code (event subscribed twice due to the automatic
> subscription), and they are not very useful there.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/claudemr/entitysysd/pull/7#issuecomment-188811516

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by claudemr** [comment]
And I'm not sure that ECS lib would fit in a larger game (I have not enough experience in that).

In my todo list, I plan to have an cache-oblivious implementation (using an SList of free id's for the entities is pretty bad) and use maybe std.allocator to be GC-free. But that would require some proper benchmarks to be really useful. Would it be worth the effort? That's the question... :)

**Comment by rcorre** [comment]
Pretty much my opinion :)
There are certainly areas for improvement but I'm not going to worry about it until I actually see a performance problem and can actually trace it to EntitySysD.

**Pull request closed without merging**
